config/routes.rb
Rails.application.routes.draw do

  resources :call_logs
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'members#index'
  resources :members
  resources :call_logs
  resources :appointments do
    collection do
      post 'create_appointment'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/call_log.rb
class CallLog < ApplicationRecord
  belongs_to :member
  belongs_to :user
  has_many :appointments
  has_many :completed_gaps

  #accepts_nested_attributes_for :appointments, :completed_gaps
  accepts_nested_attributes_for :appointments, reject_if: :all_blank, allow_destroy: true

end

app/controllers/call_logs_controller.rb
class CallLogsController < ApplicationController
  before_action :set_call_log, only: [:show, :edit, :update, :destroy]

  # GET /call_logs
  # GET /call_logs.json
  def index
    @call_logs = CallLog.all
  end

  # GET /call_logs/1
  # GET /call_logs/1.json
  def show
  end

  # GET /call_logs/new
  def new
    @call_log = CallLog.new
  end

  # GET /call_logs/1/edit
  def edit
  end

  # POST /call_logs
  # POST /call_logs.json
  def create
    @call_log = CallLog.new(call_log_params)

    respond_to do |format|
      if @call_log.save
        format.html { redirect_to @call_log, notice: 'Call log was successfully created.' }
        format.json { render :show, status: :created, location: @call_log }
      else
        format.html { render :new }
        format.json { render json: @call_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /call_logs/1
  # PATCH/PUT /call_logs/1.json
  def update
    respond_to do |format|
      if @call_log.update(call_log_params)
        format.html { redirect_to @call_log, notice: 'Call log was successfully updated.' }
        format.json { render :show, status: :ok, location: @call_log }
      else
        format.html { render :edit }
        format.json { render json: @call_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /call_logs/1
  # DELETE /call_logs/1.json
  def destroy
    @call_log.destroy
    respond_to do |format|
      format.html { redirect_to call_logs_url, notice: 'Call log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_call_log
    @call_log = CallLog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def call_log_params
    params.require(:call_log).permit(:comments,
                                     :member_id,
                                     :time_of_call,
                                     :user_id,
                                     :result_of_call,
                                     :pcp_provider_call,
                                     appointments_attributes:
                                         [:id,
                                          :member_id,
                                          :doctor_id,
                                          :date_of_visit,
                                          :transportation_required,
                                          :_destroy])
  end
end

app/helpers/call_logs_helper.rb
module CallLogsHelper

  def result_of_call_selections
    ['Successful',
     'Left voicemail',
     'Unable to Reach or Leave Msg',
     'Wrong Number',
     'Phone Disconnected',
     'Busy signal',
     'Requested a call back'].sort
  end

  def pcp_call_selections
    ['N/A',
     'No',
     'Scheduled appointment',
     'Unable to schedule at this time',
     'Office is closed',
     'Wrong number for office']
  end
end

app/views/call_logs/_appointment.html.erb
<div class="modal-content">
  <h4>Add Appointment</h4>
  <%= f.input :member_id, input_html: { value: f.object.member_id } %>
  <%= f.text_field :date_of_visit, class: 'datepicker' %>
</div>
<div class="modal-footer">
  <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
</div>

app/views/call_logs/_appointment_fields.html.erb
<li class="nested-fields">
  <div class="collapsible-header">
    <span class="badge">
    <%= link_to_remove_association "<i class='material-icons'>clear</i>".html_safe, f,
                                   { class: 'waves-effect waves-light' } %>
    </span>
    <span><i class="material-icons">event_note</i></span>
    appt 1
  </div>
  <div class="collapsible-body">
    <%= f.association :doctor, label_method: :display_name, value_method: :id, include_blank: 'Please Select...', wrapper_html: { class: 'm6 s12' } %>
    <div class="row">
      <div class="input-field">
        <%= f.label :date_of_visit %>
        <%= f.text_field :date_of_visit, class: 'datepicker' %>
      </div>
    </div>
    <%= f.label :transportation_required %>
    <%= f.collection_radio_buttons :transportation_required, [[true, 'Yes'], [false, 'No']], :first, :last %>
  </div>
</li>

app/views/call_logs/_form.html.erb
<%= simple_form_for @call_log, html: { class: 'col s6' } do |f| %>
    <%= f.error_notification %>

    <%= f.association :member, label_method: :display_name, value_method: :id, include_blank: 'Please Select...' %>
    <%= f.label :date_of_call %>
    <%= f.text_field :date_of_call, class: 'datepicker' %>
    <div class="row">
      <div class="input-field">
        <%= f.time_select :time_of_call, { time_separator: '', value: Time.now }, class: 'col s2' %>
        <%= f.label :time_of_call %>
      </div>
    </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.input :result_of_call, collection: result_of_call_selections %>
    <%= f.input :pcp_provider_call, collection: pcp_call_selections %>

    <!-- Modal Trigger -->
    <ul class="collapsible" data-collapsible="accordion">
      <%= f.simple_fields_for :appointments do |appt| %>
          <%= render 'appointment_fields', f: appt %>
      <% end %>
    </ul>

    <div class="links">
      <%= link_to_add_association 'add appointment', f,
                                  :appointments,
                                  { 'data-association-insertion-node' => "ul.collapsible",
                                    'data-association-insertion-method' => "append",
                                    'data-turbolinks' =>"false",
                                    class: 'waves-effect waves-light btn' } %>
    </div>

    <%= f.input :comments, input_html: { class: 'materialize-textarea' } %>

    <%= f.button :submit %>
    <%= link_to 'Back', call_logs_path, class: 'btn' %>
<% end %>

<div id="appt_modal" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Appointment</h4>
    <div class="row">
      <div class="input-field col s12">
        <%= text_field :appointment, :date_of_visit, class: 'datepicker' %>
        <%= label :appointment, 'Date of Visit' %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= link_to "Create Appointment", '#!', class: 'modal-action modal-close waves-effect waves-green btn create_appointment' %>
  </div>
</div>

app/views/call_logs/edit.html.erb
<h1>Editing Call Log</h1>

<%= render 'form', call_log: @call_log %>

<%= link_to 'Show', @call_log %> |
<%= link_to 'Back', call_logs_path %>

app/views/call_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Call Logs</h1>

<table>
  <thead>
    <tr>
      <th>Comments</th>
      <th>Member</th>
      <th>Time of call</th>
      <th>User</th>
      <th>Result of call</th>
      <th>Pcp provider call</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @call_logs.each do |call_log| %>
      <tr>
        <td><%= call_log.comments %></td>
        <td><%= call_log.member %></td>
        <td><%= call_log.time_of_call %></td>
        <td><%= call_log.user %></td>
        <td><%= call_log.result_of_call %></td>
        <td><%= call_log.pcp_provider_call %></td>
        <td><%= link_to 'Show', call_log %></td>
        <td><%= link_to 'Edit', edit_call_log_path(call_log) %></td>
        <td><%= link_to 'Destroy', call_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call Log', new_call_log_path %>

app/views/call_logs/new.html.erb
<h1>New Call Log</h1>

<%= render 'form' %>

<%#= link_to 'Back', call_logs_path %>

app/views/call_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comments:</strong>
  <%= @call_log.comments %>
</p>

<p>
  <strong>Member:</strong>
  <%= @call_log.member %>
</p>

<p>
  <strong>Time of call:</strong>
  <%= @call_log.time_of_call %>
</p>

<p>
  <strong>User:</strong>
  <%= @call_log.user %>
</p>

<p>
  <strong>Result of call:</strong>
  <%= @call_log.result_of_call %>
</p>

<p>
  <strong>Pcp provider call:</strong>
  <%= @call_log.pcp_provider_call %>
</p>

<%= link_to 'Edit', edit_call_log_path(@call_log) %> |
<%= link_to 'Back', call_logs_path %>