config/routes.rb
Rails.application.routes.draw do

  resources :call_logs
  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'members#index'
  resources :members
  resources :call_logs
  resources :appointments do
    collection do
      post 'create_appointment'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :primary_care_physician, class_name: 'Doctor'
  has_many :appointments
  has_many :call_logs
  has_and_belongs_to_many :care_gaps
  has_many :completed_gaps
  validates :id_number, presence: true
  validates :id_number, uniqueness: true

  def display_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:last_name, :first_name, :middle_initial, :id_number, :date_of_birth, :gender, :home_number, :cell_number, :address, :alternate_address, :date_of_enrollment, :date_of_disenrollment, :line_of_business, :primary_language, :interpreter_needed, :ethnicity, :marital_status)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for member, html: { class: 'form-horizontal col-md-6' } do |f| %>
    <%= f.error_notification %>
    <%= f.input :last_name %>
    <%= f.input :first_name, label: 'First Name' %>
    <%= f.input :middle_initial %>
    <%= f.input :id_number %>
    <%= f.input :date_of_birth %>
    <div class="form-group row">
      <%= f.label :gender,class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <div class="checkbox">
          <input type="hidden" name="member[gender]" value="">
          <span class="radio inline">
            <label for="member_gender_true" class="form-check-inline">
              <input class="radio_buttons optional form-check-input" type="radio" value="true" checked="checked" name="member[gender]" id="member_gender_true">
              M
            </label>
        </span>
          <span class="radio inline">
            <label for="member_gender_false" class="form-check-inline">
              <input class="radio_buttons optional form-check-input" readonly="readonly" type="radio" value="false" name="member[gender]" id="member_gender_false">
              F
            </label>
        </span>
        </div>
      </div>
    </div>
    <%#= f.input :gender,:collection => [[true, 'M'], [false, 'F']],
          :label_method => :last, 
          :value_method => :first,
          :as => :radio_buttons, 
          :item_wrapper_class => 'inline',
          :checked => true %>
    <%= f.input :home_number %>
    <%= f.input :cell_number %>
    <%= f.input :address %>
    <%= f.input :alternate_address %>
    <%= f.input :date_of_enrollment %>
    <%= f.input :date_of_disenrollment %>
    <%= f.input :line_of_business %>
    <%= f.input :primary_language %>
    <%#= f.input :interpreter_needed %>
    <div class="form-group row">
      <%= f.label :interpreter_needed,class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <div class="checkbox">
          <input type="hidden" name="member[interpreter_needed]" value="">
          <span class="radio inline">
            <label for="member_interpreter_needed_true" class="form-check-inline">
              <input class="radio_buttons optional form-check-input" type="radio" value="true" checked="checked" name="member[interpreter_needed]" id="member_interpreter_needed_true">
              Yes
            </label>
        </span>
          <span class="radio inline">
            <label for="member_interpreter_needed_false" class="form-check-inline">
              <input class="radio_buttons optional form-check-input" readonly="readonly" type="radio" value="false" name="member[interpreter_needed]" id="member_interpreter_needed_false">
              No
            </label>
        </span>
        </div>
      </div>
    </div>
    <%= f.input :ethnicity %>
    <%= f.input :marital_status, collection: [ "Married", "Single", "Divorced", "Widowed"] %>
    <%= f.button :submit %>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Members</h1>

<table class="highlight">
  <thead>
  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Middle initial</th>
    <th>Id number</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @members.each do |member| %>
      <tr>
        <td><%= member.last_name %></td>
        <td><%= member.first_name %></td>
        <td><%= member.middle_initial %></td>
        <td><%= link_to member.id_number, member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<div class='row'>
<%= render 'form', member: @member %>
</div>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Middle initial:</strong>
  <%= @member.middle_initial %>
</p>

<p>
  <strong>Id number:</strong>
  <%= @member.id_number %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @member.date_of_birth %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @member.gender %>
</p>

<p>
  <strong>Home number:</strong>
  <%= @member.home_number %>
</p>

<p>
  <strong>Cell number:</strong>
  <%= @member.cell_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @member.address %>
</p>

<p>
  <strong>Alternate address:</strong>
  <%= @member.alternate_address %>
</p>

<p>
  <strong>Date of enrollment:</strong>
  <%= @member.date_of_enrollment %>
</p>

<p>
  <strong>Date of disenrollment:</strong>
  <%= @member.date_of_disenrollment %>
</p>

<p>
  <strong>Line of business:</strong>
  <%= @member.line_of_business %>
</p>

<p>
  <strong>Primary language:</strong>
  <%= @member.primary_language %>
</p>

<p>
  <strong>Interpreter needed:</strong>
  <%= @member.interpreter_needed %>
</p>

<p>
  <strong>Ethnicity:</strong>
  <%= @member.ethnicity %>
</p>

<p>
  <strong>Marital status:</strong>
  <%= @member.marital_status %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>